-- Fresh schema for menu-service, derived from the JPA entities:
--   ee.ut.esi.quickbite.menu.domain.MenuItem  (@Table "menu_item")
--   ee.ut.esi.quickbite.menu.domain.Price     (@Embeddable -- columns merged into menu_item)
--
-- MenuItem.menuItemId is a UUID generated by the application (`UUID.randomUUID()`
-- in the constructor) -- there is no @GeneratedValue, the DB never assigns one.
-- MenuItem.restaurantId is a UUID cross-service reference to restaurant-service;
-- there is no DB-level FK because the two services own separate databases.
--
-- Hibernate ddl-auto is set to `validate`, so this file is the single source
-- of truth. Column types and nullability mirror the @Column annotations.

CREATE TABLE menu_item (
    menu_item_id   UUID            NOT NULL,
    restaurant_id  UUID            NOT NULL,
    name           VARCHAR(255)    NOT NULL,
    description    VARCHAR(2000),
    -- @Embedded Price -- amount + currency live as flat columns on menu_item.
    price_amount   NUMERIC(19, 2)  NOT NULL,
    price_currency VARCHAR(3)      NOT NULL,
    category       VARCHAR(100)    NOT NULL,
    is_available   BOOLEAN         NOT NULL,
    created_at     TIMESTAMP(6)    NOT NULL,
    updated_at     TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_menu_item PRIMARY KEY (menu_item_id),
    -- Defensive: the service rejects non-positive prices in code
    -- (MenuService.validatePrice), but enforce at the DB too so a stray
    -- direct insert can't poison the catalog.
    CONSTRAINT chk_menu_item_price_positive CHECK (price_amount > 0)
);

-- Index the foreign-key-by-convention column and the category, since both
-- drive the only list/filter query (MenuItemRepository.searchForRestaurant).
CREATE INDEX idx_menu_item_restaurant ON menu_item (restaurant_id);
CREATE INDEX idx_menu_item_category   ON menu_item (category);
