-- Fresh schema for order-service, derived from the JPA entities:
--   ee.ut.anup.orderservice.entity.Order       (@Table "orders")
--   ee.ut.anup.orderservice.entity.OrderItem   (@Table "order_items")
--   ee.ut.anup.orderservice.entity.BaseEntity  (mapped superclass: createdAt/By, updatedAt/By)
--
-- Order.orderId and OrderItem.orderItemId are Long auto-increment row ids
-- (GenerationType.IDENTITY -> Postgres "GENERATED BY DEFAULT AS IDENTITY").
-- Order.userId is UUID -- the value lives in the JWT's userId claim and
-- references users(user_id) in user-service. There is no FK across services.
-- OrderItem.order is @ManyToOne @JoinColumn(name="order_id") with cascade=ALL
-- on Order.items -- the DB FK has ON DELETE CASCADE to mirror that.
--
-- Hibernate ddl-auto is set to `validate`, so this file is the single source
-- of truth. Column types mirror what Hibernate 6 would generate from the
-- entities on PostgreSQL (BigDecimal -> NUMERIC(38,2), Long -> BIGINT,
-- Integer -> INTEGER, LocalDateTime -> TIMESTAMP(6), String -> VARCHAR(255),
-- UUID -> UUID). Nullability matches the entity (no @Column(nullable=false)
-- on these fields), since validate mode compares against the entity model.

-- =========================
-- orders
-- =========================
CREATE TABLE orders (
    order_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    user_id       UUID,
    restaurant_id VARCHAR(255),
    status        VARCHAR(255),
    total_amount  NUMERIC(38, 2),
    -- BaseEntity audit columns
    created_at    TIMESTAMP(6),
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP(6),
    updated_by    VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE INDEX idx_orders_user_id       ON orders (user_id);
CREATE INDEX idx_orders_restaurant_id ON orders (restaurant_id);

-- =========================
-- order_items
-- =========================
CREATE TABLE order_items (
    order_item_id BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    order_id      BIGINT,
    menu_item_id  VARCHAR(255),
    name          VARCHAR(255),
    unit_price    NUMERIC(38, 2),
    quantity      INTEGER,
    created_at    TIMESTAMP(6),
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP(6),
    updated_by    VARCHAR(255),
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
