-- Fresh schema for restaurant-service, derived from the JPA entities:
--   ee.ut.esi.quickbite.restaurant.domain.Restaurant  (@Table "restaurant")
--   ee.ut.esi.quickbite.restaurant.domain.Location    (@Embeddable -- columns merged into restaurant)
--
-- Restaurant.restaurantId is a UUID generated by the application
-- (`UUID.randomUUID()` in the entity constructor) -- no @GeneratedValue,
-- the DB never assigns one.
-- Restaurant.ownerId is a UUID cross-service reference to user-service's
-- users(user_id); there is no DB-level FK because the two services own
-- separate databases.
--
-- Hibernate ddl-auto is set to `validate`, so this file is the single source
-- of truth. Column types and nullability mirror the @Column annotations.

CREATE TABLE restaurant (
    restaurant_id   UUID            NOT NULL,
    owner_id        UUID            NOT NULL,
    name            VARCHAR(255)    NOT NULL,
    -- @Embedded Location -- address/city/latitude/longitude flatten onto restaurant.
    address         VARCHAR(255),
    city            VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    operating_hours VARCHAR(20),
    is_open         BOOLEAN         NOT NULL,
    created_at      TIMESTAMP(6)    NOT NULL,
    updated_at      TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (restaurant_id)
);

-- Drives the only filtered list query in RestaurantRepository (find owners'
-- restaurants for menu-management screens) and the optional city browse.
CREATE INDEX idx_restaurant_owner ON restaurant (owner_id);
CREATE INDEX idx_restaurant_city  ON restaurant (city);
