CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255),
    is_default BOOLEAN NOT NULL,
    label VARCHAR(255),
    postal_code VARCHAR(255),
    street VARCHAR(255),
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS driver_profile (
    user_id BIGINT PRIMARY KEY,
    is_available BOOLEAN NOT NULL,
    license_number VARCHAR(255),
    vehicle_type VARCHAR(255)
);

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS uk_users_email;
ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS chk_users_role;
ALTER TABLE users
    ADD CONSTRAINT chk_users_role
    CHECK (role IN ('CUSTOMER', 'DRIVER', 'RESTAURANT_OWNER', 'ADMIN'));

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS chk_users_status;
ALTER TABLE users
    ADD CONSTRAINT chk_users_status
    CHECK (status IN ('ACTIVE', 'SUSPENDED'));

ALTER TABLE address
    DROP CONSTRAINT IF EXISTS fk_address_user;
ALTER TABLE address
    ADD CONSTRAINT fk_address_user
    FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE driver_profile
    DROP CONSTRAINT IF EXISTS fk_driver_profile_user;
ALTER TABLE driver_profile
    ADD CONSTRAINT fk_driver_profile_user
    FOREIGN KEY (user_id) REFERENCES users (user_id);
