-- Fresh schema for user-service, derived from the JPA entities:
--   entity.ee.ut.quickbite.userservice.User
--   entity.ee.ut.quickbite.userservice.Address
--   entity.ee.ut.quickbite.userservice.DriverProfile
--
-- User.userId is a native UUID generated by Hibernate (GenerationType.UUID).
-- Address.addressId is a Long auto-increment row id; address.user_id is the
-- FK back to users.user_id (UUID, matching the parent PK).
-- DriverProfile shares its PK with User via @MapsId, so driver_profile.user_id
-- is both the primary key AND the foreign key.
--
-- Hibernate ddl-auto is set to `validate`, so this file is the single source
-- of truth for the schema. Column types and constraints below mirror what
-- Hibernate 6 would generate from the entities on PostgreSQL.

-- =========================
-- users
-- =========================
CREATE TABLE users (
    user_id      UUID         NOT NULL,
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    full_name    VARCHAR(255),
    phone_number VARCHAR(255),
    role         VARCHAR(255),
    status       VARCHAR(255),
    created_at   TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role
        CHECK (role IS NULL OR role IN ('CUSTOMER', 'DRIVER', 'RESTAURANT_OWNER')),
    CONSTRAINT chk_users_status
        CHECK (status IS NULL OR status IN ('ACTIVE', 'SUSPENDED'))
);

-- =========================
-- address
-- =========================
-- @ManyToOne(LAZY) @JoinColumn(name="user_id") on Address.user. No cascade
-- DDL flag, but Address belongs to User in JPA (User.addresses uses
-- orphanRemoval=true + CascadeType.ALL), so ON DELETE CASCADE on the FK
-- keeps DB-level deletes consistent with JPA's expectation.
CREATE TABLE address (
    address_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id      UUID,
    street       VARCHAR(255),
    city         VARCHAR(255),
    postal_code  VARCHAR(255),
    label        VARCHAR(255),
    is_default   BOOLEAN      NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (address_id),
    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_address_user_id ON address (user_id);

-- =========================
-- driver_profile
-- =========================
-- @OneToOne @MapsId @JoinColumn(name="user_id") -- the PK column is also
-- the FK column. The driver profile lives and dies with its user.
CREATE TABLE driver_profile (
    user_id        UUID         NOT NULL,
    vehicle_type   VARCHAR(255),
    license_number VARCHAR(255),
    is_available   BOOLEAN      NOT NULL,
    CONSTRAINT pk_driver_profile PRIMARY KEY (user_id),
    CONSTRAINT fk_driver_profile_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);
