spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5435/delivery_db
    username: delivery_user
    password: delivery_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8086

services:
  payment:
    url: http://localhost:8085

jwt:
  secret: ${JWT_SECRET:dGVzdC1zZWNyZXQtZm9yLWRldi1vbmx5LWRvLW5vdC11c2UtaW4tcHJvZC0xMjM0NTY=}
  issuer: ${JWT_ISSUER:quickbite-user-service}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
